name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update packages
        run: sudo apt-get update
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - name: Install
        run: npm ci
      - name: Unit tests
        run: npm run unit
      - name: e2e tests
        run: npm run github:wdio
